
<?php 
function themeOptions ($themeOption)
{
	switch ($themeOption)
	{

	    /* background color and Pattern */
	    
	    
	    case 'background_pattern':
		return Mage::getStoreConfig('mygeneral/background/background_pattern', Mage::app()->getStore()->getId());
	    break; 
	    case 'background_color':
		return Mage::getStoreConfig('mygeneral/background/background_color', Mage::app()->getStore()->getId());
	    break;
	    case 'background_image':
		return Mage::getStoreConfig('mygeneral/background/background_image', Mage::app()->getStore()->getId());
	    break;
	    case 'bg_repeat':
		return Mage::getStoreConfig('mygeneral/background/bg_repeat', Mage::app()->getStore()->getId());
	    break;  
	    case 'bg_attachment':
		return Mage::getStoreConfig('mygeneral/background/bg_attachment', Mage::app()->getStore()->getId());
	    break;  
	    case 'bg_position_x':
		return Mage::getStoreConfig('mygeneral/background/bg_position_x', Mage::app()->getStore()->getId());
	    break; 
	    case 'bg_position_y':
		return Mage::getStoreConfig('mygeneral/background/bg_position_y', Mage::app()->getStore()->getId());
	    break;   
	
	
    
	    /* PRODUCT LIST */
     
	    case 'column_count':
		return Mage::getStoreConfig('mygeneral/product_list/column_count', Mage::app()->getStore()->getId());
	    break;
	    case 'productlayout':
		return Mage::getStoreConfig('mygeneral/product_list/productlayout', Mage::app()->getStore()->getId());
	    break;
	    case 'product_hover_effects':
		return Mage::getStoreConfig('mygeneral/product_list/product_hover_effects', Mage::app()->getStore()->getId());
	    break;
        
            /* COLORS */
            
            case 'active_color':
                return Mage::getStoreConfig('mygeneral/colors/active_color');
             break;
	     case 'secondary_color':
                return Mage::getStoreConfig('mygeneral/colors/active_color');
             break;
           
	   /*  Extra settings */
	
	     
	     case 'ajaxcart':
                return Mage::getStoreConfig('mygeneral/extra_settings/ajaxcart');
             break;

	}
}
?>



<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<meta name="viewport" content="width=device-width" />

<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<?php
function is_mobile()
{
	$ua = strtolower($_SERVER['HTTP_USER_AGENT']);
	$mobiles = array("android", "iphone", "ipod", "ipad",
		"blackberry", "palm", "mobile", "mini", "kindle");
	foreach($mobiles as $mobile)
	{
		if(strpos($ua,$mobile)) return true;
	}
	return false;
}
?>
<script>
	function successMessage(message,message1,message2)
		{
		    jQuery('body').append('<div class="alert"><button class="close"></button></div>');
		    var $alert = jQuery('.alert');
		    $alert.fadeIn(400);
		    $alert.append(message);
		    $alert.html(message1).append('<a class="close" href="<?php echo $this->getUrl('checkout/cart') ?>">GO TO CART</a>');
		    $alert.html(message2).append('<a class="close">CONTINUE SHOPPING</a>');
		    jQuery('.close').click(function () {
			$alert.fadeOut(400);
		    });
		//    $alert.fadeIn('400', function () {
		//	setTimeout(function () {
		//	    $alert.fadeOut('400', function () {
		//		jQuery(this).fadeOut(400, function(){ jQuery(this).detach(); })
		//	    });
		//	}, 10000)
		//    });
		}
</script>


<?php 
$color = Array();
$color['active_color'] = '
.header .welcome-msg ,
.middle_part h1,
.add_box .old-price .price,
#nav li a:hover,
#nav li ul li a:hover,
#nav li ul li ul li a span:hover,
#nav li.level-top:hover,
.col_left dt,
.block-compare .block-title,
.block-tags .block-title,
.detail_product_blog h1,
.tabs li.active a span,
.tabs li a:hover,
div.ajaxcartpro_progress p, div.ajaxcartpro_progress1 p,
.cart .page-title h1,
.cart-table .product-name a:hover,
.cart .discount h2, .cart .shipping h2,
.cart .crosssell h2,
.page-title h1, .page-title h2,
#opc-login .form-list li.control label,
.account-login .content h2,
.fieldset .legend,
.dashboard .box-info .box-head h2,
.block-account .block-title,
.block-account .block-content li.current,
.block-reorder .block-title,
.addresses-list h2,
.my-wishlist .product-name a,
.block-viewed .block-title,
.block-poll .block-title,
.block-wishlist .block-title,
.block-reorder .block-title,
.block-compared .block-title
';

$border = Array();
$border['active_border'] = '
.tital,
#footer_part .footer_hr,
#nav li ul li a,
.col_left dt,
.block-compare .block-title,
.block-tags .block-title,
.data-table tr.last th, .data-table tr.last td,
.block-progress .block-title,
.block-compared .block-title,
.block-viewed .block-title,
.block-poll .block-title,
.block-wishlist .block-title,
.block-reorder .block-title,
.block-account .block-title
';

$border_top = Array();
$border_top['active_topborder'] = '
#nav li.over, #nav li:hover,
#nav li.active,
.tabs li:hover,
.tabs li.active

';

$border_bottom = Array();
$border_bottom['active_bottomborder'] = '
.custom_menu h1,
#nav li ul li a:hover

';

$button = Array();
$button['active_background'] = '

.banner .text_box a.button,
.flex .text_box a.button,
.pager .pages .current,
.pager .pages a:hover,
.button.button,
a.btn_listing_price,
a.btn_view_listing,
a.btn_product-options,
.buttons-set .button,
.box-tags button.tag,
button.btn-checkout,
.cart .discount button, .cart .shipping button,
.buttons-set .button,
.block-poll button.button, 
.block-reorder button.button,
.my-wishlist button.btn-cart,
.block-wishlist .block-content li .product-details a.link-cart,
#footer_part .box_button,
.cart-table .btn-continue:hover,
.cart-table .btn-update:hover, .cart-table .btn-empty:hover,
a.btn_view_listing,
a.btn_listing_price_position,
.product-options a.btn:hover,
.cart-table a.btn:hover,
.form-search .search-autocomplete li.selected

';


$div = Array();
$div['background'] = '

.shopping_bg,
.opc .active .step-title,
.block-progress dt.complete,
.block-cart .subtotal,
.block-cart .btn-remove, .block-cart .btn-edit,
.btn-remove,
.dashboard .box-tags .number,
.dashboard .box-reviews .number,
div.alert,
.quick-view

';

$font = Array();
$font['title_font'] = '
.middle_part h1,
.page-title h1,
.page-title h2,
.detail_product_blog h1,
.cart .page-title h1,
.banner .text_box h1
';

$font['content_font'] = 'body, input,select,textarea,button';

$maskcolor = Array();
$maskcolor['mask_color'] = '
.view-first .mask
';


$background_color = themeOptions('background_color');
$background_pattern = themeOptions('background_pattern');
$background_image = themeOptions('background_image');

$bodyfont = Mage::getStoreConfig('gfont/gfont_config/bodyfont');
$titlefont = Mage::getStoreConfig('gfont/gfont_config/titlefont');

$producthovereffects = themeOptions('product_hover_effects');


    function jsString($str='') { 
        return trim(preg_replace("/('|\"|\r?\n)/", '', $str)); 
    }     
?>
<?php
function html2rgb($rgb)
{
    if ($rgb[0] == '#')
        $rgb = substr($rgb, 1);

    if (strlen($rgb) == 6)
        list($r, $g, $b) = array($rgb[0].$rgb[1],
                                 $rgb[2].$rgb[3],
                                 $rgb[4].$rgb[5]);
    elseif (strlen($rgb) == 3)
        list($r, $g, $b) = array($rgb[0].$rgb[0], $rgb[1].$rgb[1], $rgb[2].$rgb[2]);
    else
        return false;

    $r = hexdec($r); $g = hexdec($g); $b = hexdec($b);
 
    return array($r, $g, $b);
}

?>

<!--<script type="text/javascript">-->
<!--    var active_color_selector = '<?php echo jsString($color['active_color']); ?>';-->
<!--    var active_bg_selector = '<?php echo jsString($button['active_background']).','.jsString($div['background']); ?>';-->
<!--    -->
<!--    var active_color_default = '15BBBC';-->
<!--    var bg_selector = 'body';-->
<!--    var bg_default = 'ffffff';-->
<!--		-->
<!--    var content_font_selector = '<?php echo jsString($font['content_font']); ?>';-->
<!--    var content_font_default = "<?php echo $bodyfont; ?>";-->
<!--		-->
<!--    var title_font_selector = '<?php echo jsString($font['title_font']); ?>';-->
<!--    var title_font_default = "<?php echo $titlefont; ?>"; //"'KaushanScript Regular'";-->
<!--		-->
<!--    var banner_selector = '.fluid_container';-->
<!--		//var banner_default = "1000";-->
<!---->
<!--    var pattern_default = 'url(<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>/pattern/pattern9.png)';-->
<!--   -->
<!--</script>-->


<!-- Active Color -->

<?php $hex =  "#".themeOptions('active_color'); 
$val = html2rgb($hex);
?>


    <style type="text/css">
        /* Active Color */
        <?php echo jsString($color['active_color']); ?>              { color: #<?php echo themeOptions('active_color') ?>; }
	
	<?php echo jsString($border['active_border']); ?>              { border-color: #<?php echo themeOptions('active_color') ?>; }
	
	<?php echo jsString($border_top['active_topborder']); ?>              { border-top-color:  #<?php echo themeOptions('active_color') ?>; }
	
	<?php echo jsString($border_bottom['active_bottomborder']); ?>              { border-bottom-color:  #<?php echo themeOptions('active_color') ?>; }
        
        /* Active Background */
        <?php echo jsString($button['active_background']); ?>         {  background-color: #<?php echo themeOptions('active_color') ?>;}
        
         <?php echo jsString($button['active_background']); ?>        {  box-shadow: 0 0 0px 1px #<?php echo themeOptions('active_color') ?>; }
	 
	 <?php echo jsString($div['background']); ?>         {  background-color: #<?php echo themeOptions('active_color') ?>;}
    </style>

<!-- Background Option -->


        <?php
    if(isset($background_color) && $background_color != null){  ?>
	
	<style>
            body
                {
                    background:#<?php echo themeOptions('background_color') ?>;
                }
        </style><?php	}
        
    elseif(isset($background_pattern) && $background_pattern != null){ ?>
        <style>
            body
                {
                    background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'pattern/'.themeOptions('background_pattern') ?>);
                }    
        </style><?php }
        
    elseif(isset($background_image) && $background_image != null){ ?>
        <style>
                body            
                {
                        background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'custom/image/'.themeOptions('background_image') ?>);
                        background-attachment: <?php echo themeOptions('bg_attachment') ?>;
                         background-position: <?php echo themeOptions('bg_position_y') ?> <?php echo themeOptions('bg_position_x') ?>;
                        background-repeat: <?php echo themeOptions('bg_repeat') ?>;
                }    
        </style>
    <?php } else{} ?>


<!-- Google Fonts -->


        <?php
    if(isset($bodyfont) && $bodyfont != null && $bodyfont != '--select--' && $bodyfont != 'Segoe UI Regular')
        {  ?>
            <link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $bodyfont); ?>' rel='stylesheet' type='text/css'>
            <style>
            <?php echo jsString($font['content_font']); ?> {font-family: '<?php echo $bodyfont; ?>';}
            </style>
        <?php
        }
	
    if(isset($titlefont) && $titlefont != null && $titlefont != '--select--' && $titlefont != 'Segoe UI Regular')
        {
            
        ?>
	<link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $titlefont); ?>' rel='stylesheet' type='text/css'>
            <style>
            <?php echo jsString($font['title_font']); ?>                  { font-family: '<?php echo $titlefont; ?>'; }
            </style>
        <?php
        }?>

	<?php
	if(isset($titlefont) && $titlefont = 'Segoe UI Regular')
        {
            
        ?>
	
            <style>
            <?php echo jsString($font['title_font']); ?>                  { font-family: '<?php echo $titlefont; ?>'; }
            </style>
        <?php
        }?>
	
	<?php
    if(isset($bodyfont) && $bodyfont = 'Segoe UI Regular')
        {  ?>
           
            <style>
            <?php echo jsString($font['content_font']); ?> {font-family: '<?php echo $bodyfont; ?>';}
            </style>
        <?php
        } ?>


<?php
if ($producthovereffects == 2)
{
?>
	<style type="text/css">
	@media (min-width: 999px)
	{
		.view-first:hover .mask { opacity: 0; display: none; }
		
		.view-first:hover img {
					-moz-transform: none;
					-webkit-transform: none;
					-o-transform: none;
					-ms-transform: none;
				    
				    }
	}
	</style>
<?php
}
else if ($producthovereffects == 1)
{
	?>
	<style type="text/css">
	@media (min-width: 999px)
	{
		
		.view-first .mask 	{
			-moz-transition:none;
			-webkit-transition: none;
			-o-transition: none;
			-ms-transition: none;
			transition: none;
		}
		
		.view-first:hover .mask {
						top:183px;
						position:  absolute;
						overflow: hidden;
						padding-top:10px;
						padding-bottom:10px;
						bottom: 0;
						left: 0;
					}
		
		.product_btn 	{
					margin-top: 0px;
					padding-top: 10px;
				}
		.product_btn.last {
					margin-top: 15px;
				}
				.view .mask, .view .content {height: auto;}
				.women_price_box3 .view .mask, .view .content{height: auto;}
				.women_price_box4 .view .mask, .view .content{height: auto;}
	}
	</style>
	<?php
}



