

<?php $ajaxcart = themeOptions('ajaxcart'); ?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="product_like_box">
    <div class="tital">		
    	<div class="hr"><h1><?php echo $this->__('Product you may like') ?></h1></div>	
    </div>
    <div class="errow_iphone">
	    <a href="#next" class="next btn btn_arrow btn_right_arrow" title="Next" onclick="j$('#upsell-product-carousel').touchCarousel('next');"></a>
	    <a href="#prev" class="prev btn btn_arrow btn_left_arrow" title="Preview" onclick="j$('#upsell-product-carousel').touchCarousel('prev');"></a>
    </div>
    
    <div class="clear"></div>
    <div id="upsell-product-carousel" class="ui-carousel module ui-touchCarousel ui-touchCarousel-horizontal ui-touchCarousel-items-3 ui-touchCarousel-rows-1">
    <div class="carousel-mask">
        <ul class="ui-draggable">
        <?php $i=1; $_columnCount = count($this->getItemCollection()->getItems()); ?>
        <?php foreach($this->getItems() as $_link): ?>
            <li class="arrivals_price_box item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                
                <div class="view view-first">	
			    
			    <?php if($ajaxcart == '2') { ?>
			    <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_link->getId()));?>' class='fancybox quick-view' id='fancybox<?php echo $_link->getId()?>'><?php echo $this->__('Quick-View') ?></a>
			    <?php } ?>
			    				
			   <a href="<?php echo $_link->getProductUrl() ?>" class="product-image"> <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(181,272) ?>" width="181" height="272" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /> </a>
			    	
			    <div class="sale">
                               <?php $cdate = date('Y-m-d');  //echo 'frpm:-'.$_link->special_from_date.'----';echo "to:-".$_link->special_to_date.'--';
								    $a= 0;
								    if($_link->special_from_date != null && $_link->special_to_date == "")
								    {
									if( $cdate >= $_link->special_from_date)
									{
										$a = 1; 
									}
								    }
								    if($_link->special_from_date != "" && $_link->special_to_date != "")
								    {
									if($cdate >= $_link->special_from_date && $cdate <= $_link->special_to_date)
									{
									$a = 1; 
									}
								    }
									if($a == 1){ ?>
								       <div class="sale_img"></div>
									<?php } 
								    ?>

                                 
                                 
                                <?php if($this->getReviewsSummaryHtml($_link) != null): ?>
				<div class="star_img"><?php echo $this->getReviewsSummaryHtml($_link) ?></div>
                                <?php endif; ?>
			    </div>
                           
			    <div class="mask">
								
				<div class="product_btn">
				    <?php if($_link->isSaleable()): ?>
					<?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
					    <?php if ( !($_link->getTypeInstance(true)->hasRequiredOptions($_link) || $_link->isGrouped()) ) { ?>
					    <a href="#add-to-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_link) ?>','<?php echo $_link->getId()?>')" class="btn-cart ajx-cart btn_view btn_add_bag btn_add_bag_position info" title="<?php echo $this->__('Buy now') ?>"><?php echo $this->__('Add To Bag') ?></a>
					    
					    <?php } else { ?>
						    <a href="#add-to-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')" class="btn-cart btn_view btn_add_bag btn_add_bag_position info" title="<?php echo $this->__('Buy now') ?>"><?php echo $this->__('Add To Bag') ?></a>
						    
					    <?php }  ?>
					<?php } else { ?>
					    <a href="#add-to-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')" class="btn-cart btn_view btn_add_bag btn_add_bag_position info" title="<?php echo $this->__('Buy now') ?>"><?php echo $this->__('Add To Bag') ?></a>
					<?php } ?>
				    <?php else: ?>
					<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
				    <?php endif; ?>
				</div>
                                 
								
				<div class="product_btn last">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
				    <a href="<?php echo $this->getAddToWishlistUrl($_link) ?>" class="btn_view btn_view_product btn_view_product_1 info" title="<?php echo $this->__('Add to Wishlist') ?>"></a>
                                    <?php endif; ?>
                                    
				    <a href="<?php echo $_link->getProductUrl() ?>" class="btn_view btn_view_product btn_view_product_2 info" title="<?php echo $this->__('View Details') ?>"></a>
				    
                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_link)): ?>
                                    <a href="<?php echo $_compareUrl ?>" class="btn_view btn_view_product btn_view_product_3 info" title="<?php echo $this->__('Add to Compare') ?>"></a>
                                    <?php endif; ?>
								
				</div>					     
				
			    </div>
			    
				
		</div>
                <?php 
									$productName = $this->htmlEscape($_link->getName());
									if(strlen($productName) > 25) {
										$productName = mb_strimwidth($productName,0,25,"...",'utf-8');
									}
		?>
                <p><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $productName; ?></a></p>
				
		<div class="clear"></div>
				
		<div class="add_box">
				
		<h2><?php echo $this->getPriceHtml($_link, true, '-upsell') ?></h2>
					
		</div>
                <div id='ajax_loader<?php echo $_link->getId()?>' class="ajaxcartpro_progress" style="display: none;">
			    <img src="<?php echo $this->getSkinUrl('ajaxcart/images/al.gif'); ?>">
			    <p><?php echo $this->__('Please wait...') ?></p>
			    <div><?php echo $this->__('We are updating Shopping Bag.') ?></div>
			</div>
                
            </li>
            <?php $i++; endforeach ?>
        </ul>
        </div>
    </div>
    
</div>

<script type="text/javascript">//decorateTable('upsell-product-table')</script>
<script type="text/javascript">
					
				//j$(function(){
				
					var opts = {};
						opts['itemsPerTransition'] = 1;
						opts['pagination'] = false;
						opts['nextPrevActions'] = false;
                                                
						
						carousel = j$('#upsell-product-carousel');
						carousel.touchCarousel(opts);
						
				//});
		</script>
<?php endif ?>


<script type="text/javascript">
     <?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
	jQuery.noConflict();
	
	jQuery('.fancybox').live('click', function() {
        jQuery('#fancybox-loading').show();
        });
	
	jQuery('.fancybox').fancybox(
			{
			   hideOnContentClick : true,
			   width: 650,
			   autoDimensions: true,
               type : 'iframe',
			   showTitle: false,
			   scrolling: 'no',
			   onComplete: function(){
				jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
				    jQuery('#fancybox-loading').hide();
					jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
					jQuery.fancybox.resize();
				 });

			   }
			}
		);
	
	function showOptions(id){
		jQuery('#fancybox'+id).trigger('click');
	}
		
	function setAjaxData(data,iframe){
		if(data.status == 'ERROR'){
			alert(data.message);
		}else{
		    successMessage(data.message);
			if(jQuery('.block-cart')){
	            jQuery('.block-cart').replaceWith(data.sidebar);
	        }
	        if(jQuery('.header .links')){
	            jQuery('.header .links').replaceWith(data.toplink);
	        }
	        jQuery.fancybox.close();
		}
	}
	function setLocationAjax(url,id){
		url += 'isAjax/1';
		url = url.replace("checkout/cart","ajax/index");
		jQuery('#ajax_loader'+id).show();
		try {
			jQuery.ajax( {
				url : url,
				dataType : 'json',
				success : function(data) {
					jQuery('#ajax_loader'+id).hide();
         			setAjaxData(data,false);           
				}
			});
		} catch (e) {
		}
	}
	 <?php } ?>
</script>
